version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    volumes:
      #MAC
      #- /Users/bzatrok/Downloads/output_reports:/tmp/output_reports
      #Windows
      - /c/Users/Public/output_reports:/tmp/output_reports
  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always